apiVersion: v1
kind: PersistentVolume
metadata:
  name: retail-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /var/nfs/general/retail-mysql
    server: 15.206.158.9