apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: retail-dynamic-pvc
  namespace: capsule-ns
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: retail-sc